### PR TITLE
(#12) use real Date.now to avoid using potentially mocked one

### PR DESCRIPTION
**Pull request by valignatev**
This is the PR for #12 

I decided to go with mostly copy-pasting test cases for being more explicit with them. Their async matter already hard enough to understand even without extracting common parts, but if you insist, I'll do this :)

What do you think?

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Seems legit 👍

**Comment by lgandecki** [comment]
Yup, I'm about to merge and release a new version. I realized that circleci wasn't set up to run on forks, I turned it on now but I think I have to manually verify the branch. 
I want to add semantic release here first as well and will use this PR as the test that it's set up properly. 

Thanks @valignatev for the work! (if you are around, could you possibly do something like

```
git commit --allow-empty -m "Trigger circleci"
```

to trigger the circleci build?

**Comment by valignatev** [comment]
@lgandecki Sure, done. It failed though. Locally `npm run test` passes. I guess I should satisfy 
`tsc --emitDeclarationOnly && babel src --out-dir lib --extensions ".ts,.tsx"`, right?

**Comment by lgandecki** [comment]
it fails on npm run build, not tests (as you probably noticed). did you try to build it locally? :)

Feel free to play around and try to fix the typescript issues (probably a good learning experience), if it's over your head, me or someone from my team can take a look shortly.

**Comment by valignatev** [comment]
> did you try to build it locally

You got me, I totally overlooked it.
> probably a good learning experience

Oh yeah, you're right, I'm a total typescript noob :)
But it's fixed now. I referred to this discussion in typescript repo: https://github.com/Microsoft/TypeScript/issues/19816

> This is a. inconvenient and b. not easy to find if you are new to TS. Here is a list of issues we have so far related to this issue:

They're right, this is not that easy to find :) But I think it's better than casting `window` to `any`. In the test I'm fairly happy to silence the tsc though because I feel that dancing around typescript damages readability of the test. What do you think?

**Comment by lgandecki** [comment]
I think that's a work very well done, I love that you added the tests, and comments that explain "why" instead of "what". I will do my best to merge this in tomorrow.
Thanks!

**Pull request merged**
